# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7773d541c8c1b4ccae5ba75f908b78dd0a03a4f000397e6b808ae05d9e77d67f6ac70dc36fd4bb678bd0dbc7d3f0bcca2dc24cfd407a14b24fb29e5e2212de6

test:
  secret_key_base: d49872ab6515c3cdf23a8240b592ef6c229656d01275e30b06769bf5910b9ec48e87581190211f1105196ae4677b9f87e390a1e12c4c6a7f8a884897399dd802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
